# Generated by Django 4.1.4 on 2022-12-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(default='name', max_length=64)),
                ('chart_id', models.CharField(default='chart-id', max_length=64, unique=True)),
                ('chart_data', models.CharField(default='{"x":[],"y":[]}', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
